name: flutter_dynamic_translator
description: "A Flutter plugin for dynamic translation based on locale files."
version: 1.0.3
homepage: https://github.com/flutter-translator/flutter-dynamic-translator
repository: https://github.com/flutter-translator/flutter-dynamic-translator
issue_tracker: https://github.com/flutter-translator/flutter-dynamic-translator/issues
license: MIT

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_dynamic_translator
        pluginClass: FlutterDynamicTranslatorPlugin
      ios:
        pluginClass: FlutterDynamicTranslatorPlugin
      web:
        pluginClass: FlutterDynamicTranslatorPlugin
        fileName: flutter_dynamic_translator_web.dart
      windows:
        pluginClass: FlutterDynamicTranslatorPlugin
      macos:
        pluginClass: FlutterDynamicTranslatorPlugin
      linux:
        pluginClass: FlutterDynamicTranslatorPlugin
